### ISSUE TITLE
您好，请问用RPBPBR脚本分析后，如何对应到每个细胞上

### ISSUE THREAD

**Issue by ChristopherLeeZG** [sunlightwang/RPBPBR#2]
我是读了最近一篇Resolving Fates and Single-Cell Transcriptomes of Hematopoietic Stem Cell Clones by PolyloxExpress
Barcoding，知道了这个repo。想用RPBPBR脚本分析一下这篇文章的数据
![image](https://user-images.githubusercontent.com/40749917/95807331-7c53d600-0d3c-11eb-97d6-1d2e32693737.png)
这是example里的例子结果。请问，如何对应到每个细胞上。
谢谢！！

最后，
![image](https://user-images.githubusercontent.com/40749917/95807513-f2583d00-0d3c-11eb-9c79-8fbdd28394b0.png)
这是我分析上面提到的文章中的结果，是不是我应该改掉脚本中的adapter？

**Comment by sunlightwang** [comment]
RPBPBR中的test数据是采用的bulk数据，所以不涉及到对应到单细胞的问题。单细胞数据中，我们利用Cell index来对应barcode和转录组。分析单细胞数据RPBPBR需要一些小改动，这部分会在不久后发布。如果需要进一步沟通，请email联系我：sunlightwang at gmail.com

**Comment by ChristopherLeeZG** [comment]
非常感谢您的回复，很好的文章。我会持续关注的🙂
